package com.myspace.loan_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Amount")
	private int amount;
	@org.kie.api.definition.type.Label(value = "Approval")
	private boolean approval;
	@org.kie.api.definition.type.Label(value = "Duration")
	private int duration;
	@org.kie.api.definition.type.Label(value = "Interrest Rate")
	private double interestRate;
	@org.kie.api.definition.type.Label(value = "Reason")
	private java.lang.String reason;

	public Loan() {
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public boolean isApproval() {
		return this.approval;
	}

	public void setApproval(boolean approval) {
		this.approval = approval;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public double getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(double interestRate) {
		this.interestRate = interestRate;
	}

	public java.lang.String getReason() {
		return this.reason;
	}

	public void setReason(java.lang.String reason) {
		this.reason = reason;
	}

	public Loan(int amount, boolean approval, int duration,
			double interestRate, java.lang.String reason) {
		this.amount = amount;
		this.approval = approval;
		this.duration = duration;
		this.interestRate = interestRate;
		this.reason = reason;
	}

    
}